══════════════════════════════════════════════════════════════
  POWER QUERY (M Language) — مخصص لبياناتك
  افتح Power BI → Transform Data → Advanced Editor
  وانسخ كل كود في جدوله
══════════════════════════════════════════════════════════════

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[1] Fact_Orders — جدول الحقائق الرئيسي
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
let
    Source = Excel.Workbook(File.Contents("C:\SupplyChain\Data\SupplyChain_Cleaned_Master.xlsx"), null, true),
    Sheet = Source{[Item="Fact_Orders",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),

    // أنواع البيانات
    Typed = Table.TransformColumnTypes(Headers, {
        {"order_id",                  Int64.Type},
        {"order_item_id",             Int64.Type},
        {"customer_id",               Int64.Type},
        {"product_card_id",           Int64.Type},
        {"order_date_dateorders",     type datetime},
        {"shipping_date_dateorders",  type datetime},
        {"sales",                     type number},
        {"order_profit_per_order",    type number},
        {"order_item_quantity",       Int64.Type},
        {"order_item_discount",       type number},
        {"order_item_discount_rate",  type number},
        {"order_item_product_price",  type number},
        {"order_item_profit_ratio",   type number},
        {"order_item_total",          type number},
        {"benefit_per_order",         type number},
        {"sales_per_customer",        type number},
        {"days_for_shipping_real",    Int64.Type},
        {"days_for_shipment_scheduled", Int64.Type},
        {"shipping_delay_days",       Int64.Type},
        {"late_delivery_risk",        Int64.Type},
        {"order_year",                Int64.Type},
        {"order_month",               Int64.Type}
    }),

    // عمود المفتاح للتاريخ (للربط مع Dim_Date)
    AddDateKey = Table.AddColumn(Typed, "DateKey", 
        each Date.From([order_date_dateorders]), type date),

    // عمود Revenue بعد الخصم
    AddRevenue = Table.AddColumn(AddDateKey, "Net_Revenue",
        each [sales] - [order_item_discount], type number),

    // تصنيف الأرباح
    AddProfitTier = Table.AddColumn(AddRevenue, "Profit_Tier",
        each if [order_item_profit_ratio] > 0.3 then "High"
             else if [order_item_profit_ratio] > 0.1 then "Medium"
             else if [order_item_profit_ratio] > 0    then "Low"
             else "Loss",
        type text)

in
    AddProfitTier


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[2] Dim_Customer — بُعد العميل
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
let
    Source = Excel.Workbook(File.Contents("C:\SupplyChain\Data\SupplyChain_Cleaned_Master.xlsx"), null, true),
    Sheet = Source{[Item="Dim_Customer",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"customer_id",       Int64.Type},
        {"customer_city",     type text},
        {"customer_country",  type text},
        {"customer_segment",  type text},
        {"customer_state",    type text},
        {"market",            type text}
    }),
    // إضافة منطقة العميل الكاملة
    AddFullLocation = Table.AddColumn(Typed, "Customer_Full_Location",
        each [customer_city] & ", " & [customer_country], type text)
in
    AddFullLocation


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[3] Dim_Product — بُعد المنتج
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
let
    Source = Excel.Workbook(File.Contents("C:\SupplyChain\Data\SupplyChain_Cleaned_Master.xlsx"), null, true),
    Sheet = Source{[Item="Dim_Product",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"product_card_id",     Int64.Type},
        {"product_name",        type text},
        {"product_price",       type number},
        {"product_status",      Int64.Type},
        {"category_id",         Int64.Type},
        {"category_name",       type text},
        {"department_id",       Int64.Type},
        {"department_name",     type text},
        {"product_category_id", Int64.Type}
    }),
    AddAvailability = Table.AddColumn(Typed, "Stock_Status",
        each if [product_status] = 0 then "In Stock" else "Out of Stock", type text),
    AddPriceRange = Table.AddColumn(AddAvailability, "Price_Range",
        each if [product_price] < 50   then "Budget (<$50)"
             else if [product_price] < 200 then "Mid ($50–$200)"
             else if [product_price] < 500 then "Premium ($200–$500)"
             else "Luxury (>$500)", type text)
in
    AddPriceRange


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[4] Dim_Order — بُعد الطلب
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
let
    Source = Excel.Workbook(File.Contents("C:\SupplyChain\Data\SupplyChain_Cleaned_Master.xlsx"), null, true),
    Sheet = Source{[Item="Dim_Order",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"order_id",       Int64.Type},
        {"order_status",   type text},
        {"order_region",   type text},
        {"order_country",  type text},
        {"order_city",     type text},
        {"order_state",    type text},
        {"shipping_mode",  type text},
        {"delivery_status",type text},
        {"type",           type text}
    }),
    AddStatusGroup = Table.AddColumn(Typed, "Status_Group",
        each if Text.Contains([order_status], "COMPLETE") then "Completed"
             else if Text.Contains([order_status], "CANCEL") then "Cancelled"
             else if Text.Contains([order_status], "FRAUD") then "Fraud"
             else if Text.Contains([order_status], "PENDING") then "Pending"
             else "Other", type text),
    AddDeliveryFlag = Table.AddColumn(AddStatusGroup, "Delivery_Risk_Flag",
        each if [delivery_status] = "Late delivery" then "At Risk" else "Normal", type text)
in
    AddDeliveryFlag


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[5] Dim_Date — جدول التاريخ
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
let
    Source = Excel.Workbook(File.Contents("C:\SupplyChain\Data\SupplyChain_Cleaned_Master.xlsx"), null, true),
    Sheet = Source{[Item="Dim_Date",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"Date",         type date},
        {"Year",         Int64.Type},
        {"Month_Num",    Int64.Type},
        {"Month_Name",   type text},
        {"Quarter",      type text},
        {"Day_of_Week",  type text},
        {"Week_Number",  Int64.Type},
        {"Is_Weekend",   type logical},
        {"Year_Month",   type text}
    }),
    AddFiscalQ = Table.AddColumn(Typed, "Fiscal_Quarter",
        each "FY" & Text.From([Year]) & "-" & [Quarter], type text)
in
    AddFiscalQ


━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[6] Web_Access_Logs — سجلات الموقع
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
let
    Source = Excel.Workbook(File.Contents("C:\SupplyChain\Data\SupplyChain_Cleaned_Master.xlsx"), null, true),
    Sheet = Source{[Item="Web_Access_Logs",Kind="Sheet"]}[Data],
    Headers = Table.PromoteHeaders(Sheet, [PromoteAllScalars=true]),
    Typed = Table.TransformColumnTypes(Headers, {
        {"product",      type text},
        {"category",     type text},
        {"date",         type datetime},
        {"month",        type text},
        {"hour",         Int64.Type},
        {"department",   type text},
        {"ip",           type text},
        {"url",          type text},
        {"is_add_to_cart", Int64.Type},
        {"year",         Int64.Type},
        {"month_num",    Int64.Type}
    }),
    AddActionType = Table.AddColumn(Typed, "Action_Type",
        each if [is_add_to_cart] = 1 then "Add to Cart" else "Product View", type text),
    AddHourGroup = Table.AddColumn(AddActionType, "Hour_Group",
        each if [hour] < 6  then "Night (0–5)"
             else if [hour] < 12 then "Morning (6–11)"
             else if [hour] < 18 then "Afternoon (12–17)"
             else "Evening (18–23)", type text)
in
    AddHourGroup
